name: Generate and Commit M3U8 Playlist

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-tvplus:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        pip install --no-cache-dir -r requirements.txt

    - name: Run Samsung TV Plus App
      run: |
        nohup python app.py --PORT 8183 &

    - name: Wait for App to Start
      run: sleep 15

    - name: Fetch M3U8 Playlist
      run: curl http://127.0.0.1:8183/playlist.m3u8 -o playlist.m3u8

    - name: Commit and Push M3U8 Playlist
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add playlist.m3u8
        git commit -m "Add generated M3U8 playlist"
        git push
